/**
 * Shared form option constants extracted from InputForm.
 * Reusable by any component that needs filing status or state dropdowns.
 */

export const FILING_STATUS_OPTIONS = [
  { value: "single", label: "Single" },
  { value: "married_filing_jointly", label: "Married filing jointly" },
];

export const STATE_OPTIONS = [
  { value: "none", label: "Federal only (no state tax)" },
  { value: "AL", label: "Alabama (up to 5%)" },
  { value: "AK", label: "Alaska (no state tax)" },
  { value: "AZ", label: "Arizona (2.5%)" },
  { value: "AR", label: "Arkansas (up to 3.9%)" },
  { value: "CA", label: "California (up to 13.3%)" },
  { value: "CO", label: "Colorado (4.4%)" },
  { value: "CT", label: "Connecticut (up to 6.99%)" },
  { value: "DE", label: "Delaware (up to 6.6%)" },
  { value: "DC", label: "District of Columbia (up to 10.75%)" },
  { value: "FL", label: "Florida (no state tax)" },
  { value: "GA", label: "Georgia (5.19%)" },
  { value: "HI", label: "Hawaii (up to 11%)" },
  { value: "ID", label: "Idaho (5.3%)" },
  { value: "IL", label: "Illinois (4.95%)" },
  { value: "IN", label: "Indiana (3%)" },
  { value: "IA", label: "Iowa (3.8%)" },
  { value: "KS", label: "Kansas (up to 5.58%)" },
  { value: "KY", label: "Kentucky (4%)" },
  { value: "LA", label: "Louisiana (3%)" },
  { value: "ME", label: "Maine (up to 7.15%)" },
  { value: "MD", label: "Maryland (up to 5.75%)" },
  { value: "MA", label: "Massachusetts (5% / 9%)" },
  { value: "MI", label: "Michigan (4.25%)" },
  { value: "MN", label: "Minnesota (up to 9.85%)" },
  { value: "MS", label: "Mississippi (4.4%)" },
  { value: "MO", label: "Missouri (up to 4.7%)" },
  { value: "MT", label: "Montana (up to 5.9%)" },
  { value: "NE", label: "Nebraska (up to 5.2%)" },
  { value: "NV", label: "Nevada (no state tax)" },
  { value: "NH", label: "New Hampshire (no state tax)" },
  { value: "NJ", label: "New Jersey (up to 10.75%)" },
  { value: "NM", label: "New Mexico (up to 5.9%)" },
  { value: "NY", label: "New York (up to 10.9%)" },
  { value: "NC", label: "North Carolina (4.25%)" },
  { value: "ND", label: "North Dakota (up to 2.5%)" },
  { value: "OH", label: "Ohio (up to 3.5%)" },
  { value: "OK", label: "Oklahoma (up to 4.75%)" },
  { value: "OR", label: "Oregon (up to 9.9%)" },
  { value: "PA", label: "Pennsylvania (3.07%)" },
  { value: "RI", label: "Rhode Island (up to 5.99%)" },
  { value: "SC", label: "South Carolina (up to 6.2%)" },
  { value: "SD", label: "South Dakota (no state tax)" },
  { value: "TN", label: "Tennessee (no state tax)" },
  { value: "TX", label: "Texas (no state tax)" },
  { value: "UT", label: "Utah (4.65%)" },
  { value: "VT", label: "Vermont (up to 8.75%)" },
  { value: "VA", label: "Virginia (up to 5.75%)" },
  { value: "WA", label: "Washington (no state tax)" },
  { value: "WV", label: "West Virginia (up to 4.82%)" },
  { value: "WI", label: "Wisconsin (up to 7.65%)" },
  { value: "WY", label: "Wyoming (no state tax)" },
  { value: "custom", label: "Other (enter rate)" },
];
